import type { BatchPromptConfig } from '../types';

export const p0MotionConfigs: BatchPromptConfig[] = [
  {
    phetName: 'Forces and Motion: Basics',
    neonId: 'forces-motion-basics',
    title: { en: 'Forces and Motion: Basics', zh: '力与运动基础' },
    category: 'motion',
    tier: 'P0',
    isUpgrade: false,
    concepts: ["Newton's First Law", "Newton's Second Law", 'net force', 'friction'],
    equations: ['F_{net} = ma', 'f = \\mu N', 'a = \\frac{F_{net}}{m}'],
    variables: [
      { name: 'appliedForce', label: 'Applied Force', unit: 'N', min: 0, max: 500, default: 100, step: 10 },
      { name: 'mass', label: 'Mass', unit: 'kg', min: 1, max: 200, default: 50, step: 5 },
      { name: 'friction', label: 'Friction Coefficient', unit: '', min: 0, max: 1, default: 0.3, step: 0.05 },
    ],
    visualElements: [
      'Person or hand pushing a box on a surface',
      'Force arrows (applied, friction, normal, gravity) with magnitude labels',
      'Motion trail showing velocity',
      'Real-time velocity and acceleration display',
    ],
    scenarios: ['Frictionless ice surface', 'Rough sandpaper surface', 'Tug of war (two opposing forces)'],
    phetBenchmark: 'Apply force to objects, see acceleration, understand F=ma with friction',
    mustExceed: ['3D perspective vs PhET 2D', 'Real-time force diagram update', 'Multiple simultaneous force arrows with magnitude labels'],
    apStandards: ['3.A.1', '3.B.1'],
    gradeLevel: 'Grade 9-12',
  },
  {
    phetName: 'Friction',
    neonId: 'friction-lab',
    title: { en: 'Friction Lab', zh: '摩擦力实验室' },
    category: 'motion',
    tier: 'P0',
    isUpgrade: false,
    concepts: ['Static friction', 'kinetic friction', 'normal force', 'friction coefficient', 'inclined plane'],
    equations: ['f_s \\leq \\mu_s N', 'f_k = \\mu_k N', 'N = mg\\cos\\theta'],
    variables: [
      { name: 'mass', label: 'Mass', unit: 'kg', min: 1, max: 100, default: 10, step: 1 },
      { name: 'angle', label: 'Surface Angle', unit: '°', min: 0, max: 60, default: 0, step: 1 },
      { name: 'muStatic', label: 'μₛ (static)', unit: '', min: 0.1, max: 1.5, default: 0.5, step: 0.05 },
      { name: 'muKinetic', label: 'μₖ (kinetic)', unit: '', min: 0.05, max: 1.0, default: 0.3, step: 0.05 },
    ],
    visualElements: [
      'Block on inclined plane (3D with adjustable tilt)',
      'Normal force arrow (perpendicular to surface)',
      'Friction force arrow (along surface)',
      'Weight decomposition (mg sinθ and mg cosθ)',
      'Friction vs applied force graph (showing static→kinetic transition)',
    ],
    scenarios: ['Flat surface + increasing push force', 'Inclined plane (find critical angle)', 'Material comparison: ice vs rubber vs sandpaper'],
    phetBenchmark: 'Explore static and kinetic friction on flat and inclined surfaces',
    mustExceed: ['3D tilting plane with smooth animation', 'Real-time friction graph showing static→kinetic transition', 'Material selector with visual texture change'],
    apStandards: ['3.B.1', '3.B.2'],
    gradeLevel: 'Grade 9-12',
  },
  {
    phetName: 'Gravity and Orbits',
    neonId: 'gravity-orbits',
    title: { en: 'Gravity and Orbits', zh: '万有引力与轨道' },
    category: 'motion',
    tier: 'P0',
    isUpgrade: false,
    concepts: ['Universal gravitation', 'orbital velocity', 'escape velocity', "Kepler's laws"],
    equations: ['F = G\\frac{m_1 m_2}{r^2}', 'v_{orbit} = \\sqrt{\\frac{GM}{r}}', 'T^2 = \\frac{4\\pi^2}{GM}r^3'],
    variables: [
      { name: 'starMass', label: 'Star Mass', unit: 'M☉', min: 0.1, max: 10, default: 1, step: 0.1 },
      { name: 'planetMass', label: 'Planet Mass', unit: 'M⊕', min: 0.1, max: 100, default: 1, step: 0.5 },
      { name: 'orbitalRadius', label: 'Orbital Radius', unit: 'AU', min: 0.2, max: 5, default: 1, step: 0.1 },
      { name: 'initialVelocity', label: 'Initial Velocity', unit: 'km/s', min: 0, max: 50, default: 29.8, step: 0.5 },
    ],
    visualElements: [
      'Central star (glowing emissive material)',
      'Orbiting planet with trail (color gradient showing speed)',
      'Gravitational field lines or gradient',
      'Velocity and acceleration vectors on planet',
      'Orbit path prediction (dotted line)',
    ],
    scenarios: ['Earth-Sun (circular orbit)', 'Comet (highly elliptical orbit)', 'Binary stars', 'Escape trajectory'],
    phetBenchmark: 'Observe orbital paths with adjustable mass and velocity',
    mustExceed: ['Full 3D orbit visualization', 'Trail color gradient showing speed', "Kepler's law sweep area visualization"],
    apStandards: ['3.C.1', '3.C.2'],
    gradeLevel: 'Grade 11-12',
  },
  {
    phetName: 'Pendulum Lab',
    neonId: 'pendulum-lab',
    title: { en: 'Pendulum Lab', zh: '单摆实验室' },
    category: 'motion',
    tier: 'P0',
    isUpgrade: false,
    concepts: ['Simple harmonic motion', 'period', 'restoring force', 'energy conservation in pendulum'],
    equations: ['T = 2\\pi\\sqrt{\\frac{L}{g}}', '\\theta(t) = \\theta_0 \\cos(\\omega t)', 'E = mgh = \\frac{1}{2}mv^2'],
    variables: [
      { name: 'length', label: 'String Length', unit: 'm', min: 0.1, max: 3, default: 1, step: 0.05 },
      { name: 'mass', label: 'Bob Mass', unit: 'kg', min: 0.1, max: 5, default: 1, step: 0.1 },
      { name: 'gravity', label: 'Gravity', unit: 'm/s²', min: 1, max: 20, default: 9.8, step: 0.1 },
      { name: 'angle0', label: 'Initial Angle', unit: '°', min: 5, max: 90, default: 30, step: 1 },
    ],
    visualElements: [
      '3D pendulum bob on string',
      'Angle arc indicator',
      'Velocity vector at bob',
      'Energy bar chart (KE blue / PE red / Total green dashed)',
      'Period measurement display',
    ],
    scenarios: ['Earth (g=9.8)', 'Moon (g=1.6)', 'Jupiter (g=24.8)', 'Large angle (non-linear regime)'],
    phetBenchmark: 'Adjust length, mass, gravity; measure period; observe energy transfer',
    mustExceed: ['3D swing visualization with smooth physics', 'Side-by-side energy bar chart updating in real-time', 'Analytical vs numerical overlay for small angle'],
    apStandards: ['3.B.3'],
    gradeLevel: 'Grade 9-12',
  },
  {
    phetName: 'Masses and Springs',
    neonId: 'masses-springs',
    title: { en: 'Masses and Springs', zh: '质量与弹簧' },
    category: 'motion',
    tier: 'P0',
    isUpgrade: false,
    concepts: ["Hooke's law", 'spring constant', 'SHM', 'natural frequency', 'damping'],
    equations: ['F = -kx', 'T = 2\\pi\\sqrt{\\frac{m}{k}}', 'x(t) = A\\cos(\\omega t + \\phi)', '\\omega = \\sqrt{\\frac{k}{m}}'],
    variables: [
      { name: 'springK', label: 'Spring Constant', unit: 'N/m', min: 10, max: 500, default: 100, step: 10 },
      { name: 'mass', label: 'Hanging Mass', unit: 'kg', min: 0.1, max: 10, default: 1, step: 0.1 },
      { name: 'damping', label: 'Damping', unit: '', min: 0, max: 1, default: 0, step: 0.05 },
      { name: 'displacement', label: 'Initial Displacement', unit: 'm', min: 0.01, max: 0.5, default: 0.1, step: 0.01 },
    ],
    visualElements: [
      '3D coiled spring (deformable, stretches/compresses visually)',
      'Hanging mass block',
      'Equilibrium line marker',
      'Displacement-time graph',
      'Force arrows (spring force + gravity)',
      'Energy bars (KE / PE-spring / PE-gravity)',
    ],
    scenarios: ['Soft spring + heavy mass (slow oscillation)', 'Stiff spring + light mass (fast)', 'Critical damping', 'No damping (perpetual oscillation)'],
    phetBenchmark: 'Hang masses from springs, observe oscillation, measure period',
    mustExceed: ['Realistic 3D coil deformation', 'Damping envelope visualization', 'Dual spring comparison mode'],
    apStandards: ['3.B.3'],
    gradeLevel: 'Grade 9-12',
  },
  {
    phetName: "Hooke's Law",
    neonId: 'hookes-law',
    title: { en: "Hooke's Law", zh: '胡克定律' },
    category: 'motion',
    tier: 'P0',
    isUpgrade: false,
    concepts: ["Hooke's law", 'elastic limit', 'spring constant', 'restoring force', 'elastic potential energy'],
    equations: ['F = kx', 'PE = \\frac{1}{2}kx^2', 'k = \\frac{F}{x}'],
    variables: [
      { name: 'springK', label: 'Spring Constant', unit: 'N/m', min: 10, max: 1000, default: 200, step: 10 },
      { name: 'appliedForce', label: 'Applied Force', unit: 'N', min: 0, max: 200, default: 50, step: 5 },
    ],
    visualElements: [
      'Spring with ruler overlay showing extension',
      'Force vs displacement graph (real-time, drawn as you drag)',
      'Elastic limit marker on graph',
      'PE energy bar',
      'Spring compression/extension animation',
    ],
    scenarios: ['Soft spring (k=50)', 'Stiff spring (k=500)', 'Beyond elastic limit'],
    phetBenchmark: 'Stretch and compress springs, see force-displacement relationship',
    mustExceed: ['3D spring with realistic coil physics', 'F-x graph drawn in real-time as you adjust', 'Material comparison (rubber/steel/copper)'],
    apStandards: ['3.B.3'],
    gradeLevel: 'Grade 9-12',
  },
];
